'use server';

/**
 * @fileOverview AI tool to suggest relevant blog content topics based on a given topic and language.
 *
 * - blogTopicGenerator - A function that generates blog topics.
 * - BlogTopicGeneratorInput - The input type for the blogTopicGenerator function.
 * - BlogTopicGeneratorOutput - The return type for the blogTopicGenerator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const BlogTopicGeneratorInputSchema = z.object({
  topic: z
    .string()
    .describe(
      'The central topic, keywords, or niche to generate blog ideas for.'
    ),
  language: z.enum(['Bengali', 'English']).describe('The desired language for the output.'),
});
export type BlogTopicGeneratorInput = z.infer<typeof BlogTopicGeneratorInputSchema>;

const BlogTopicGeneratorOutputSchema = z.object({
  topics: z.array(z.string()).describe('An array of 5-7 suggested blog content topics.'),
});
export type BlogTopicGeneratorOutput = z.infer<typeof BlogTopicGeneratorOutputSchema>;

export async function blogTopicGenerator(input: BlogTopicGeneratorInput): Promise<BlogTopicGeneratorOutput> {
  return blogTopicGeneratorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'blogTopicGeneratorPrompt',
  input: {schema: BlogTopicGeneratorInputSchema},
  output: {schema: BlogTopicGeneratorOutputSchema},
  prompt: `You are a blog content topic generator expert with a human touch. Your goal is to suggest topics that sound creative, engaging, and not generated by a robot.

You will suggest 5-7 blog content topics in the specified language based on the core topic provided by the user.

Core Topic/Keywords: {{{topic}}}
Language for Topics: {{{language}}}

Suggest 5-7 blog content topics that are compelling and feel like they were brainstormed by a creative human. The topics must be in the requested language ({{{language}}}).`, 
});

const blogTopicGeneratorFlow = ai.defineFlow(
  {
    name: 'blogTopicGeneratorFlow',
    inputSchema: BlogTopicGeneratorInputSchema,
    outputSchema: BlogTopicGeneratorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
