

import { Layers, RefreshCcw, Sparkles, TowerControl, Users, Youtube, Clock, TrendingUp, Award, CheckCircle, FileText, ImageIcon, Link as LinkIcon, PenSquare, ShoppingCart, Languages, Hash, Mail, Lightbulb, BarChart, GraduationCap, HelpCircle, BookCheck, DollarSign, Wand, FileSignature, Globe, Film, MessageSquare, UserCircle as UserCircleIcon, Edit, Clapperboard, Receipt, Briefcase, LayoutTemplate, Megaphone, GitBranchPlus, List, PanelTopOpen, CalendarDays, BarChart2, Quote } from 'lucide-react';

export type Tool = {
    id: string;
    title: string;
    description: string;
    href: string;
    icon: string;
    category: string;
    enabled: boolean;
};

export const allCourses = [
  {
    title: "স্মার্টফোন ও ইন্টারনেট বেসিকস",
    category: "Digital Literacy",
    instructor: "Digital Skill Hub",
    price: 0,
    level: "Beginner",
    duration: "4 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "smartphone learning",
  },
  {
    title: "বাংলায় ফ্রিল্যান্সিং শুরু",
    category: "Freelancing",
    instructor: "Abul Kalam",
    price: 49.99,
    level: "Beginner",
    duration: "12 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "freelancing laptop home",
  },
  {
    title: "ফেসবুক ও হোয়াটসঅ্যাপে ব্যবসা",
    category: "E-commerce",
    instructor: "Fatima Akhtar",
    price: 29.99,
    level: "Beginner",
    duration: "8 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "social media business",
  },
  {
    title: "হস্তশিল্প ও অনলাইন সেলস",
    category: "Home Business",
    instructor: "Rahima Begum",
    price: 39.99,
    level: "Intermediate",
    duration: "10 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "handmade crafts market",
  },
  {
    title: "স্ক্রিন রিডার ও ভয়েস টাইপিং",
    category: "Assistive Technology",
    instructor: "Jahanara Alam",
    price: 0,
    level: "Beginner",
    duration: "6 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "assistive technology computer",
  },
  {
    title: "ঘরে বসে খাবারের ব্যবসা",
    category: "Home Business",
    instructor: "Amina Khatun",
    price: 35.00,
    level: "Beginner",
    duration: "7 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "home cooking business",
  },
  {
    title: "অনলাইন টেইলরিং শপ",
    category: "Home Business",
    instructor: "Sultana Razia",
    price: 45.00,
    level: "Intermediate",
    duration: "15 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "sewing machine fabric",
  },
  {
    title: "দারাজ শপ ম্যানেজমেন্ট",
    category: "E-commerce",
    instructor: "Robiul Islam",
    price: 59.99,
    level: "Intermediate",
    duration: "10 hours",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "online store package",
  },
];

export const blogPosts = [
  {
    title: "10 Essential Skills for Modern Web Developers",
    category: "Web Development",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "developer computer code",
    author: "Jane Doe",
    date: new Date("2024-07-16").toISOString(),
    excerpt: "The web development landscape is always evolving. Here are the 10 skills you need to stay ahead of the curve in today's market.",
  },
  {
    title: "The Rise of AI: How to Leverage AI Tools for Productivity",
    category: "AI Tools",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "artificial intelligence brain",
    author: "Sarah Green",
    date: new Date("2024-07-12").toISOString(),
    excerpt: "Artificial intelligence is no longer science fiction. Discover practical AI tools that can automate tasks and boost your productivity.",
  },
  {
    title: "Building a Strong Freelance Profile That Wins Clients",
    category: "Freelancing",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "freelancer laptop cafe",
    author: "Michael Brown",
    date: new Date("2024-07-10").toISOString(),
    excerpt: "Your freelance profile is your digital storefront. Learn the secrets to crafting a compelling profile that attracts high-value clients.",
  },
  {
    title: "Color Theory for Graphic Designers: A Beginner's Guide",
    category: "Graphics Design",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "color wheel design",
    author: "John Smith",
    date: new Date("2024-07-08").toISOString(),
    excerpt: "Understand the fundamentals of color theory to create visually stunning and emotionally resonant designs.",
  }
];

export const jobPostings = [
  {
    title: "ফেসবুক পেজের জন্য সহজ পোস্ট ডিজাইন",
    client: "Local Fashion House",
    avatar: "https://placehold.co/100x100.png",
    dataAiHint: "fashion logo",
    budget: "৳৫০০",
    skills: ["Canva", "Design"],
  },
  {
    title: "বাংলা ডেটা এন্ট্রি (১০টি পেজ)",
    client: "NGO Health Project",
    avatar: "https://placehold.co/100x100.png",
    dataAiHint: "ngo logo",
    budget: "৳৮০০",
    skills: ["Data Entry", "Typing"],
  },
  {
    title: "কাস্টমার সাপোর্টের জন্য উত্তর লেখা",
    client: "E-commerce Shop",
    avatar: "https://placehold.co/100x100.png",
    dataAiHint: "shopping cart icon",
    budget: "৳১০০০",
    skills: ["Communication"],
  },
  {
    title: "হস্তশিল্পের ছবি তোলা ও এডিট করা",
    client: "Crafts Seller",
    avatar: "https://placehold.co/100x100.png",
    dataAiHint: "handmade craft",
    budget: "৳১২০০",
    skills: ["Photography", "Photo Editing"],
  },
];

export const users = [
    {
        name: "Admin User",
        email: "admin@totthoai.com",
        password: "adminpassword",
        role: "admin",
        profile_image: "https://placehold.co/100x100.png",
        plan_id: "sigma",
        credits: 9999,
        is_verified: true,
        status: "active",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        name: "Regular User",
        email: "user@totthoai.com",
        password: "userpassword",
        role: "user",
        profile_image: "https://placehold.co/100x100.png",
        plan_id: "beta",
        credits: 100,
        is_verified: true,
        status: "active",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];


export const pricingPlans = [
    {
        id: "alpha",
        name: "Alpha Plan",
        price: 499,
        originalPrice: 665,
        discount: "25% OFF",
        description: "Kickstart your content journey with powerful AI tools and essential automation.",
        credits: 100,
        validity: "15 Days",
        isPopular: false,
        features: {
            "Core Features": [
                "AI-Powered Featured Image Generation",
                "Deep Content Research",
                "One-Click Article Generator",
                "Automated Internal Linking",
                "News Article Generator",
                "Seamless WordPress Publishing",
            ],
            "Advanced Features": [
                "Topic Authority Cluster Builder",
                "Enhanced In-Content AI Images",
                "Content Refresh Tool",
                "Bulk Generation Tool"
            ],
        },
    },
    {
        id: "beta",
        name: "Beta Plan",
        price: 1499,
        originalPrice: 1998,
        discount: "25% OFF",
        description: "Scale up your output and get first dibs on future upgrades.",
        credits: 300,
        validity: "1 Month",
        isPopular: true,
        features: {
            "Core Features": [
                "AI-Powered Featured Image Generation",
                "Deep Content Research",
                "One-Click Article Generator",
                "Automated Internal Linking",
                "News Article Generator",
                "Seamless WordPress Publishing",
            ],
            "Advanced Features": [
                "Topic Authority Cluster Builder",
                "Enhanced In-Content AI Images",
                "Content Refresh Tool",
                "Bulk Generation Tool"
            ],
            "Premium Features": [
                "Early Access to Upcoming Features"
            ]
        },
    },
    {
        id: "sigma",
        name: "Sigma Plan",
        price: 4999,
        originalPrice: 6665,
        discount: "25% OFF",
        description: "Our most generous package for power users and agencies.",
        credits: 1000,
        validity: "2 Months",
        isPopular: false,
        features: {
            "Core Features": [
                "AI-Powered Featured Image Generation",
                "Deep Content Research",
                "One-Click Article Generator",
                "Automated Internal Linking",
                "News Article Generator",
                "Seamless WordPress Publishing",
            ],
            "Advanced Features": [
                "Topic Authority Cluster Builder",
                "Enhanced In-Content AI Images",
                "Content Refresh Tool",
                "Bulk Generation Tool"
            ],
            "Premium Features": [
                "Early Access to Upcoming Features",
                "Custom Feature Requests"
            ]
        },
    }
];

export const testimonials = [
     {
        feature: "Bulk Generation 2.0",
        quote: "TotthoAi 2.0's bulk generation feature is incredible! I created 50 blog posts in one afternoon using the new CSV upload. The AI images are so contextual that my engagement increased by 300%. This is the future of content creation.",
        metric: "300% engagement boost",
        authorName: "Tanvir Ahmed",
        authorRole: "Content Creator & Blogger",
        avatar: "https://placehold.co/40x40.png",
        dataAiHint: "man portrait"
    },
    {
        feature: "Content Refresh Tool",
        quote: "The Content Refresh tool saved my business! I had 200+ old articles that needed updating. TotthoAi 2.0 refreshed them all with current information and better SEO in just 2 hours. My organic traffic doubled in 3 weeks.",
        metric: "2x organic traffic",
        authorName: "Sharmin Akter",
        authorRole: "Education Platform Owner",
        avatar: "https://placehold.co/40x40.png",
        dataAiHint: "woman portrait"
    },
    {
        feature: "Authority Builder",
        quote: "The Topical Authority Builder is a game-changer! It created a complete content cluster around 'digital marketing in Bangladesh' with 25 interconnected articles. We now rank #1 for multiple keywords and our domain authority increased by 15 points.",
        metric: "15 point DA increase",
        authorName: "Fahim Rahman",
        authorRole: "News Website Owner",
        avatar: "https://placehold.co/40x40.png",
        dataAiHint: "man glasses"
    },
    {
        feature: "One-Click Writer 2.0",
        quote: "One-Click Writer 2.0 is pure magic! My team generates client content 10x faster now. The custom prompts feature ensures every piece matches our clients' brand voice perfectly. We've scaled from 5 to 50 clients without hiring more writers.",
        metric: "10x faster content",
        authorName: "Nusrat Jahan",
        authorRole: "Digital Marketing Agency",
        avatar: "https://placehold.co/40x40.png",
        dataAiHint: "woman smiling"
    }
];

export const tools: Tool[] = [
    {
        id: "one-click-writer",
        title: "One-Click Writer",
        description: "Generate a full, SEO-optimized blog post from a single title.",
        href: "/ai-tools/one-click-writer",
        icon: "Sparkles",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "blog-topic-generator",
        title: "ব্লগ টপিক জেনারেটর",
        description: "আপনার আগ্রহের উপর ভিত্তি করে সৃজনশীল ব্লগ পোস্টের ধারণা তৈরি করুন।",
        href: "/ai-tools/blog-topic-generator",
        icon: "PenSquare",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "product-description-generator",
        title: "পণ্যের বিবরণ জেনারেটর",
        description: "আপনার ই-কমার্স পণ্যের জন্য আকর্ষণীয় বিবরণ তৈরি করুন।",
        href: "/ai-tools/product-description-generator",
        icon: "ShoppingCart",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "social-media-post-generator",
        title: "সোশ্যাল মিডিয়া পোস্ট জেনারেটর",
        description: "ফেসবুক, ইনস্টাগ্রাম এবং আরও অনেক কিছুর জন্য আকর্ষণীয় পোস্ট তৈরি করুন।",
        href: "/ai-tools/social-media-post-generator",
        icon: "Hash",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "facebook-caption-generator",
        title: "ফেসবুক ক্যাপশন জেনারেটর",
        description: "আপনার ফেসবুক পোস্টের জন্য ছবি আপলোড করে আকর্ষণীয় ক্যাপশন তৈরি করুন।",
        href: "/ai-tools/facebook-caption-generator",
        icon: "MessageSquare",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "facebook-comment-generator",
        title: "ফেসবুক কমেন্ট জেনারেটর",
        description: "যেকোনো ফেসবুক পোস্টের জন্য প্রাসঙ্গিক কমেন্ট এবং রিপ্লাই তৈরি করুন।",
        href: "/ai-tools/facebook-comment-generator",
        icon: "MessageSquare",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "messenger-reply-generator",
        title: "মেসেঞ্জার রিপ্লাই জেনারেটর",
        description: "যেকোনো মেসেঞ্জার কথোপকথনের জন্য প্রাসঙ্গিক উত্তর তৈরি করুন।",
        href: "/ai-tools/messenger-reply-generator",
        icon: "MessageSquare",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "cover-letter-generator",
        title: "কভার লেটার জেনারেটর",
        description: "কয়েক সেকেন্ডের মধ্যে একটি পেশাদার কভার লেটার তৈরি করুন।",
        href: "/ai-tools/cover-letter-generator",
        icon: "FileSignature",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "ad-copy-generator",
        title: "বিজ্ঞাপনের কপি জেনারেটর",
        description: "আপনার পণ্যের জন্য আকর্ষণীয় বিজ্ঞাপনের কপি তৈরি করুন।",
        href: "/ai-tools/ad-copy-generator",
        icon: "Megaphone",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "script-writer",
        title: "স্ক্রিপ্ট লেখক",
        description: "ইউটিউব বা টিকটক ভিডিওর জন্য আকর্ষণীয় স্ক্রিপ্ট তৈরি করুন।",
        href: "/ai-tools/script-writer",
        icon: "Youtube",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "story-plot-generator",
        title: "গল্পের প্লট জেনারেটর",
        description: "আপনার পরবর্তী গল্প বা উপন্যাসের জন্য প্লট আইডিয়া তৈরি করুন।",
        href: "/ai-tools/story-plot-generator",
        icon: "GitBranchPlus",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "poetry-lyrics-maker",
        title: "কবিতা ও গান লেখক",
        description: "আপনার অনুভূতি প্রকাশ করার জন্য কবিতা বা গান লিখুন।",
        href: "/ai-tools/poetry-lyrics-maker",
        icon: "Mic",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "content-outline-generator",
        title: "কনটেন্ট আউটলাইন জেনারেটর",
        description: "যেকোনো বিষয়ের উপর ভিত্তি করে একটি সুগঠিত আউটলাইন তৈরি করুন।",
        href: "/ai-tools/content-outline-generator",
        icon: "List",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "headline-generator",
        title: "শিরোনাম জেনারেটর",
        description: "আপনার ব্লগ বা ভিডিওর জন্য আকর্ষণীয় শিরোনাম তৈরি করুন।",
        href: "/ai-tools/headline-generator",
        icon: "PanelTopOpen",
        category: "Content & Writing",
        enabled: true,
    },
    {
        id: "content-calendar-planner",
        title: "কনটেন্ট ক্যালেন্ডার প্ল্যানার",
        description: "আপনার সোশ্যাল মিডিয়া বা ব্লগের জন্য একটি কনটেন্ট ক্যালেন্ডার তৈরি করুন।",
        href: "/ai-tools/content-calendar-planner",
        icon: "CalendarDays",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "image-generator",
        title: "এআই ইমেজ জেনারেটর",
        description: "পাঠ্য থেকে লোগো, ব্যানার এবং অন্যান্য ছবি তৈরি করুন।",
        href: "/ai-tools/image-generator",
        icon: "ImageIcon",
        category: "Image Generation",
        enabled: true,
    },
    {
        id: "passport-photo-maker",
        title: "পাসপোর্ট সাইজ ছবি মেকার",
        description: "যেকোনো ছবিকে একটি পেশাদার পাসপোর্ট ছবিতে রূপান্তর করুন।",
        href: "/ai-tools/passport-photo-maker",
        icon: "UserCircleIcon",
        category: "Image Generation",
        enabled: true,
    },
     {
        id: "handwriting-extractor",
        title: "হাতের লেখা এক্সট্র্যাক্টর",
        description: "হাতে লেখা নোট থেকে টেক্সট এক্সট্র্যাক্ট করে Word, Excel বা PDF এ রূপান্তর করুন।",
        href: "/ai-tools/handwriting-extractor",
        icon: "Edit",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "video-generator",
        title: "এআই ভিডিও জেনারেটর",
        description: "পাঠ্য প্রম্পট থেকে ছোট ভিডিও তৈরি করুন।",
        href: "/ai-tools/video-generator",
        icon: "Film",
        category: "Video & Animation",
        enabled: true,
    },
    {
        id: "image-to-video-generator",
        title: "ইমেজ টু ভিডিও জেনারেটর",
        description: "একটি ছবি আপলোড করে এবং প্রম্পট দিয়ে ভিডিও তৈরি করুন।",
        href: "/ai-tools/image-to-video-generator",
        icon: "Clapperboard",
        category: "Video & Animation",
        enabled: true,
    },
    {
        id: "prompt-generator",
        title: "প্রম্পট জেনারেটর",
        description: "ছবি, ভিডিও বা অডিওর জন্য বিস্তারিত এবং কার্যকর প্রম্পট তৈরি করুন।",
        href: "/ai-tools/prompt-generator",
        icon: "Sparkles",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "professional-email-writer",
        title: "পেশাদার ইমেল লেখক",
        description: "ক্লায়েন্ট এবং সহকর্মীদের জন্য পেশাদার ইমেল ড্রাফ্ট করুন।",
        href: "/ai-tools/professional-email-writer",
        icon: "Mail",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "note-summarizer",
        title: "নোট সারাংশকারী",
        description: "দীর্ঘ পাঠ্যকে সংক্ষিপ্ত নোটে পরিণত করুন।",
        href: "/ai-tools/note-summarizer",
        icon: "BookCheck",
        category: "Productivity & Business",
        enabled: true,
    },
     {
        id: "bengali-translator",
        title: "বাংলা কনটেন্ট অনুবাদক",
        description: "ইংরেজি এবং বাংলার মধ্যে পাঠ্য অনুবাদ করুন।",
        href: "/ai-tools/bengali-translator",
        icon: "Languages",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "refund-policy-generator",
        title: "রিফান্ড পলিসি জেনারেটর",
        description: "আপনার ব্যবসার জন্য একটি কাস্টম রিফান্ড পলিসি তৈরি করুন।",
        href: "/ai-tools/refund-policy-generator",
        icon: "Receipt",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "resume-helper",
        title: "জীবনবৃত্তান্ত/সিভি সহায়ক",
        description: "একটি পেশাদার এবং কার্যকর জীবনবৃত্তান্ত লিখতে সহায়তা পান।",
        href: "/ai-tools/resume-helper",
        icon: "FileText",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "business-name-generator",
        title: "ব্যবসার নাম জেনারেটর",
        description: "আপনার নতুন ব্যবসা বা ব্র্যান্ডের জন্য সেরা নামটি খুঁজুন।",
        href: "/ai-tools/business-name-generator",
        icon: "Lightbulb",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "website-blueprint-generator",
        title: "ওয়েবসাইট ব্লুপ্রিন্ট জেনারেটর",
        description: "আপনার ধারণার জন্য একটি পৃষ্ঠা এবং বৈশিষ্ট্যসহ একটি কাঠামো তৈরি করুন।",
        href: "/ai-tools/website-blueprint-generator",
        icon: "LayoutTemplate",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "seo-keyword-suggester",
        title: "এসইও কীওয়ার্ড সাজেশনকারী",
        description: "আপনার অনলাইন দৃশ্যমানতা উন্নত করতে কীওয়ার্ড আবিষ্কার করুন।",
        href: "/ai-tools/seo-keyword-suggester",
        icon: "BarChart",
        category: "SEO & Marketing",
        enabled: true,
    },
    {
        id: "seo-score-checker",
        title: "এসইও স্কোর চেকার",
        description: "আপনার কনটেন্টের এসইও স্কোর এবং উন্নতির জন্য পরামর্শ পান।",
        href: "/ai-tools/seo-score-checker",
        icon: "BarChart2",
        category: "SEO & Marketing",
        enabled: true,
    },
    {
        id: "interview-question-practice",
        title: "ইন্টারভিউ প্রশ্ন অনুশীলন",
        description: "আপনার পরবর্তী চাকরির ইন্টারভিউর জন্য অনুশীলন প্রশ্ন তৈরি করুন।",
        href: "/ai-tools/interview-question-practice",
        icon: "Briefcase",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "freelance-idea-generator",
        title: "ফ্রিল্যান্স আইডিয়া জেনারেটর",
        description: "আপনার দক্ষতার উপর ভিত্তি করে প্রকল্পের ধারণা পান।",
        href: "/ai-tools/freelance-idea-generator",
        icon: "Wand",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "price-rate-calculator",
        title: "মূল্য/রেট ক্যালকুলেটর",
        description: "আপনার ফ্রিল্যান্স পরিষেবার জন্য একটি ন্যায্য মূল্য গণনা করুন।",
        href: "/ai-tools/price-rate-calculator",
        icon: "DollarSign",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "domain-name-suggester",
        title: "ডোমেইন নেম সাজেশনকারী",
        description: "আপনার ব্যবসা বা ওয়েবসাইটের জন্য সেরা ডোমেইন নামটি খুঁজুন।",
        href: "/ai-tools/domain-name-suggester",
        icon: "Globe",
        category: "SEO & Marketing",
        enabled: true,
    },
    {
        id: "course-recommender",
        title: "কোর্স রিকমেন্ডার",
        description: "আপনার আগ্রহের উপর ভিত্তি করে ব্যক্তিগতকৃত কোর্স সাজেশন পান।",
        href: "/ai-tools/course-recommender",
        icon: "GraduationCap",
        category: "Productivity & Business",
        enabled: true,
    },
    {
        id: "quiz-generator",
        title: "কুইজ জেনারেটর",
        description: "আপনার জ্ঞান পরীক্ষা করার জন্য যেকোনো পাঠ্য থেকে একটি কুইজ তৈরি করুন।",
        href: "/ai-tools/quiz-generator",
        icon: "HelpCircle",
        category: "Productivity & Business",
        enabled: true,
    },
];
