
"use client";

import { useState, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter, CardDescription } from "@/components/ui/card";
import { ArrowRight, Bot, PenSquare, ShoppingCart, Languages, Hash, Briefcase, Mail, Lightbulb, FileText, GraduationCap, HelpCircle, BookCheck, Image as ImageIcon, DollarSign, Wand, FileSignature, Globe, Film, Mic, Code, Presentation, Palette, Gamepad, MessageSquare, UserCircle, CornerDownRight, Clock, TrendingUp, Award, CheckCircle, Youtube, Star, Layers, RefreshCcw, TowerControl, Sparkles as SparklesIcon, Zap, PlayCircle, Users, ThumbsUp, ShieldCheck, GanttChartSquare, ChevronDown, Link as LinkIcon, Activity, ArrowUpRight, CreditCard, Check } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Separator } from "@/components/ui/separator";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import Head from 'next/head';
import { getPricingPlans, PricingPlan } from '@/services/pricing-service';
import { getTestimonials, Testimonial } from '@/services/testimonial-service';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Bar,
  BarChart,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  CartesianGrid
} from "recharts"

const userSignups = [
    { month: "Jan", signups: 186 },
    { month: "Feb", signups: 305 },
    { month: "Mar", signups: 237 },
    { month: "Apr", signups: 273 },
    { month: "May", signups: 209 },
    { month: "Jun", signups: 250 },
];

const recentActivities = [
    { name: "Olivia Martin", email: "olivia.martin@email.com", amount: "+৳499.00", type: "Subscription" },
    { name: "Jackson Lee", email: "jackson.lee@email.com", amount: "+৳1,499.00", type: "Subscription" },
    { name: "Isabella Nguyen", email: "isabella.nguyen@email.com", amount: "+৳499.00", type: "Subscription" },
    { name: "William Kim", email: "will@email.com", amount: "New User", type: "Registration" },
    { name: "Sofia Davis", email: "sofia.davis@email.com", amount: "+৳1,499.00", type: "Subscription" },
];


const faqItems = [
    {
        question: "What is TotthoAi?",
        answer: "TotthoAi is an advanced AI content generation platform designed to help content creators, marketers, and businesses create high-quality, SEO-optimized content in over 150 languages, with a special focus on Bengali."
    },
    {
        question: "How do credits work?",
        answer: "Credits are used to generate content. For example, generating a full-length article might consume a certain number of credits. Your plan determines how many credits you receive, and you can see your remaining balance in your dashboard."
    },
    {
        question: "What happens if I run out of credits?",
        answer: "If you run out of credits, you can easily upgrade to a higher plan to get more credits. You can also purchase credit packs as needed without changing your subscription."
    },
    {
        question: "How does the content generation process work?",
        answer: "Our process is simple. With the One-Click Writer, you just provide a title, and our AI handles research, writing, formatting, and even image generation. For bulk generation, you can upload a CSV file with multiple titles."
    },
    {
        question: "What types of content can TotthoAi create?",
        answer: "TotthoAi can create a wide variety of content, including blog posts, news articles, product descriptions, social media captions, professional emails, and much more. It can also generate stunning AI images."
    },
    {
        question: "Is the generated content original and plagiarism-free?",
        answer: "Yes, all content generated by TotthoAi is 100% original and passes plagiarism checks. Our AI is designed to create unique content from scratch based on the prompts and data it analyzes."
    },
     {
        question: "How do I publish content to my website?",
        answer: "We offer seamless integration with WordPress, allowing you to publish your generated articles directly to your TotthoAi dashboard."
    },
    {
        question: "What's the difference between the One-click Generator and the Bulk Content Generator?",
        answer: "The One-Click Generator is perfect for creating individual, high-quality articles quickly. The Bulk Content Generator is designed for scale, allowing you to create hundreds of articles at once by uploading a list of titles."
    },
    {
        question: "How does the Content Refresh Tool work?",
        answer: "The Content Refresh Tool analyzes your existing articles, identifies outdated information, and updates them with the latest data, improved SEO, and fresh formatting to boost their performance."
    },
    {
        question: "What image generation capabilities does TotthoAi offer?",
        answer: "Our Enhanced AI Images 2.0 can generate contextual, high-resolution images that are perfectly suited to your content, helping to increase reader engagement and visual appeal."
    },
    {
        question: "Can I customize the AI's writing style?",
        answer: "Absolutely. With our Custom AI Prompts feature, you can train the AI on your unique brand voice and writing style, ensuring all generated content is perfectly aligned with your brand."
    },
    {
        question: "Do you offer refunds if I'm not satisfied?",
        answer: "Yes, we have a refund policy. Please refer to our Refund Policy page for detailed information on the conditions and process for requesting a refund."
    },
    {
        question: "Can I upgrade or downgrade my subscription plan?",
        answer: "Yes, you can upgrade or downgrade your plan at any time directly from your account dashboard to better suit your content creation needs."
    },
    {
        question: "What support options are available?",
        answer: "We offer support via email and WhatsApp. Our dedicated support team is available to help you with any questions or issues you may have. Please visit our Contact page for more details."
    },
];

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "TotthoAi",
  "url": "https://totthoai.mojib.me/",
  "logo": "https://totthoai.mojib.me//logo.png", // Replace with your actual logo URL
  "sameAs": [
    "https://twitter.com/totthoai", // Replace with your actual social media URLs
    "https://www.facebook.com/totthoai",
    "https://www.linkedin.com/company/totthoai"
  ],
  "contactPoint": {
    "@type": "ContactPoint",
    "contactType": "customer support",
    "email": "support@totthoai.com"
  }
};


export default function Home() {
  const [pricingPlans, setPricingPlans] = useState<PricingPlan[]>([]);
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
        setLoading(true);
        const [plans, fetchedTestimonials] = await Promise.all([
            getPricingPlans(),
            getTestimonials()
        ]);
        setPricingPlans(plans);
        setTestimonials(fetchedTestimonials);
        setLoading(false);
    }
    
    fetchData();
  }, []);

  return (
    <>
      <Head>
          <script
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
          />
      </Head>
      <div className="flex flex-col bg-background">
        {/* Hero Section */}
        <section className="pt-12 md:pt-16 pb-8 md:pb-12 overflow-hidden">
          <div className="container mx-auto px-4 text-center">
              <Badge variant="secondary" className="text-sm py-1.5 px-4 border-2 border-primary/50 text-primary animate-pulse">
                  <SparklesIcon className="w-4 h-4 mr-2"/>
                  LIMITED TIME! • Get 25% OFF with code LAUNCH25
              </Badge>
              <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tight max-w-4xl mx-auto mt-4 animate-fade-in-up">
                Create Professional Content 10x Faster with AI 2.0
              </h1>
              <p className="text-lg text-muted-foreground mt-6 max-w-2xl mx-auto animate-fade-in-up [animation-delay:200ms]">
               Generate 10x faster with TotthoAi 2.0. Save 90% time, boost SEO rankings, and reach a global audience in 150+ languages.
              </p>
              
               <div className="mt-8 flex flex-wrap justify-center items-center gap-x-6 gap-y-2 text-muted-foreground font-semibold animate-fade-in-up [animation-delay:400ms]">
                  <span><Check className="w-4 h-4 inline-block mr-1 text-primary"/>SEO-optimized content</span>
                  <span><Check className="w-4 h-4 inline-block mr-1 text-primary"/>AI-generated images included</span>
                  <span><Check className="w-4 h-4 inline-block mr-1 text-primary"/>Bulk generation ready</span>
              </div>

              <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in-up [animation-delay:600ms]">
                  <Button size="lg" className="transition-transform transform hover:scale-105 w-full sm:w-auto text-base shadow-lg" asChild>
                      <Link href="/ai-tools">
                          <Zap className="mr-2 h-5 w-5"/>
                          Start Using Free Tools
                      </Link>
                  </Button>
                  <Button size="lg" variant="outline" className="transition-transform transform hover:scale-105 w-full sm:w-auto text-base" asChild>
                      <Link href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">
                          <PlayCircle className="mr-2 h-5 w-5"/>
                          Watch Demo
                      </Link>
                  </Button>
              </div>
               
               <div className="mt-8 text-center text-sm text-muted-foreground space-y-2 animate-fade-in-up [animation-delay:800ms]">
                  <p>⭐ Trusted by 3,000+ content creators • 600,000+ articles generated</p>
               </div>
          </div>
        </section>

        {/* Stats Section */}
        <section className="pt-8 pb-12 md:pb-20">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
              <Card className="p-6 bg-muted/50">
                <CardHeader>
                  <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                      <Layers className="w-8 h-8 text-primary" />
                  </div>
                  <p className="text-4xl font-bold">600,000+</p>
                </CardHeader>
                <CardContent>
                  <h3 className="text-xl font-semibold">Content Generated</h3>
                  <p className="text-muted-foreground mt-1">Articles created</p>
                </CardContent>
              </Card>
              <Card className="p-6 bg-muted/50">
                <CardHeader>
                  <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                      <Users className="w-8 h-8 text-primary" />
                  </div>
                  <p className="text-4xl font-bold">3,000+</p>
                </CardHeader>
                <CardContent>
                  <h3 className="text-xl font-semibold">Active Users</h3>
                  <p className="text-muted-foreground mt-1">Content creators</p>
                </CardContent>
              </Card>
              <Card className="p-6 bg-muted/50">
                <CardHeader>
                  <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                      <Clock className="w-8 h-8 text-primary" />
                  </div>
                  <p className="text-4xl font-bold">90%</p>
                </CardHeader>
                <CardContent>
                  <h3 className="text-xl font-semibold">Time Saved</h3>
                  <p className="text-muted-foreground mt-1">Faster than manual writing</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>


        {/* What's New Section */}
        <section id="whats-new" className="py-12 md:py-20 bg-muted/50">
          <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">What's New in TotthoAi 2.0</h2>
                  <p className="text-lg text-muted-foreground mt-4 animate-fade-in-up [animation-delay:200ms]">
                      Experience the next generation of AI-powered content creation with features designed to save time, boost quality, and scale your content strategy like never before.
                  </p>
              </div>
              <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                   <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:400ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <Clock className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">90% Time Savings</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-muted-foreground text-sm">Automate tedious tasks and generate high-quality content in seconds, not hours.</p>
                      </CardContent>
                  </Card>
                  <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:600ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <TrendingUp className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">Better SEO Results</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-muted-foreground text-sm">Create content that is optimized for search engines to rank higher and drive more traffic.</p>
                      </CardContent>
                  </Card>
                  <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:800ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <Award className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">Professional Quality</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-muted-foreground text-sm">Generate well-structured, coherent, and engaging articles that rival human writers.</p>
                      </CardContent>
                  </Card>
              </div>
          </div>
        </section>

         {/* Detailed Features */}
         <section id="features" className="py-12 md:pt-20">
              <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
                   <div className="md:col-span-2 lg:col-span-1 lg:pr-8 animate-fade-in-up">
                      <Badge variant="destructive">🔥 HOT NEW FEATURE</Badge>
                      <h3 className="text-3xl font-bold mt-2">Video to Blog Post</h3>
                      <p className="text-muted-foreground mt-4">Transform any YouTube video into a comprehensive, SEO-optimized blog post in minutes. Extract insights, create outlines, and generate complete articles from video content.</p>
                   </div>
                   <div className="md:col-span-2 grid grid-cols-2 sm:grid-cols-3 gap-8">
                      <div className="space-y-2 animate-fade-in-up [animation-delay:200ms]">
                          <ImageIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Enhanced AI Images 2.0</h4>
                          <p className="text-sm text-muted-foreground">Generate stunning, contextual images that boost engagement by 300%.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:300ms]">
                          <LinkIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Smart Internal Linking</h4>
                          <p className="text-sm text-muted-foreground">Automatically create SEO-friendly internal links to improve site authority.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:400ms]">
                          <SparklesIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Custom AI Prompts</h4>
                          <p className="text-sm text-muted-foreground">Train the AI with your unique voice and style for brand consistency.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:500ms]">
                          <Languages className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">150+ Languages Support</h4>
                          <p className="text-sm text-muted-foreground">Create content in Bengali, English, Hindi, Arabic, and more.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:600ms]">
                          <Layers className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Bulk Generation 2.0</h4>
                          <p className="text-sm text-muted-foreground">Create hundreds of articles simultaneously with our advanced engine.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:700ms]">
                          <RefreshCcw className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Content Refresh Tool</h4>
                          <p className="text-sm text-muted-foreground">Instantly update old content with fresh information and improved SEO.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:800ms]">
                          <TowerControl className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Topical Authority Builder</h4>
                          <p className="text-sm text-muted-foreground">Build topic clusters to establish your site as a niche authority.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:900ms]">
                          <PenSquare className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">One-Click Writer 2.0</h4>
                          <p className="text-sm text-muted-foreground">Generate publication-ready articles with just one click.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:1000ms]">
                          <FileText className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">News Writer 2.0</h4>
                          <p className="text-sm text-muted-foreground">Create timely, accurate news articles with real-time data integration.</p>
                      </div>
                   </div>
              </div>
               <div className="text-center mt-12 animate-fade-in-up [animation-delay:1100ms]">
                   <Button size="lg" asChild>
                      <Link href="/ai-tools">
                          <Zap className="mr-2 h-5 w-5"/>
                          Explore All Tools
                      </Link>
                  </Button>
              </div>
         </section>

        {/* AI-Generated Visuals Section */}
        <section className="py-12 md:py-20 bg-muted/50">
          <div className="container mx-auto px-4 text-center">
            <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">Enhance Your Content with AI-Generated Images</h2>
            <p className="text-lg text-muted-foreground mt-4 max-w-3xl mx-auto animate-fade-in-up [animation-delay:200ms]">
              Our AI can create stunning visuals to complement your blog posts, making your content more engaging and professional.
            </p>
            <div className="mt-12 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
              {[...Array(6)].map((_, i) => (
                <Card key={i} className="overflow-hidden group relative animate-fade-in-up" style={{animationDelay: `${400 + i * 100}ms`}}>
                  <Image src="https://placehold.co/300x400.png" alt="AI Generated Islamic Art" width={300} height={400} className="object-cover w-full h-full group-hover:scale-110 transition-transform duration-300" data-ai-hint="islamic art" />
                  <div className="absolute inset-0 bg-black/50 flex items-end p-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <p className="text-white text-sm font-semibold">AI-Generated</p>
                  </div>
                </Card>
              ))}
            </div>
            <p className="text-muted-foreground mt-8 max-w-3xl mx-auto animate-fade-in-up">
              These images are entirely generated by AI and can be seamlessly integrated into your blog posts, social media content, and marketing materials to enhance visual appeal and engagement.
            </p>
          </div>
        </section>
        
        {/* Success Stories Section */}
          <section className="py-12 md:py-20">
              <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">Success Stories with TotthoAi 2.0</h2>
                  <p className="text-lg text-muted-foreground mt-4 animate-fade-in-up [animation-delay:200ms]">
                  Real Results from Real Users. See how content creators, marketers, and businesses are achieving extraordinary results with our new 2.0 features.
                  </p>
                  <div className="mt-8 grid grid-cols-1 sm:grid-cols-3 gap-4 text-center animate-fade-in-up [animation-delay:400ms]">
                      <p className="font-semibold text-lg">Avg. 90% time savings</p>
                      <p className="font-semibold text-lg">300% faster creation</p>
                      <p className="font-semibold text-lg">2x better SEO results</p>
                  </div>
              </div>
               {loading ? (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {[...Array(4)].map((_, i) => <Skeleton key={i} className="h-64 w-full" />)}
                  </div>
               ) : (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {testimonials.map((testimonial, index) => (
                      <Card key={index} className="shadow-lg animate-fade-in-up" style={{animationDelay: `${600 + index*100}ms`}}>
                          <CardHeader>
                              <CardTitle className="text-xl">{testimonial.feature}</CardTitle>
                          </CardHeader>
                          <CardContent>
                              <p className="text-muted-foreground text-sm italic">"{testimonial.quote}"</p>
                              <p className="mt-4 font-bold text-primary">{testimonial.metric}</p>
                          </CardContent>
                          <CardFooter className="flex items-center gap-3">
                              <Avatar>
                                  <AvatarImage src={testimonial.avatar} data-ai-hint={testimonial.dataAiHint}/>
                                  <AvatarFallback>{testimonial.authorName.charAt(0)}</AvatarFallback>
                              </Avatar>
                              <div>
                                  <p className="font-semibold">{testimonial.authorName}</p>
                                  <p className="text-xs text-muted-foreground">{testimonial.authorRole}</p>
                              </div>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
              )}
              <div className="text-center mt-12 animate-fade-in-up">
                      <Button size="lg" asChild>
                      <Link href="/#pricing">
                          Start Your Success Story
                      </Link>
                  </Button>
              </div>
              </div>
          </section>

        {/* Dashboard Section from original dashboard page */}
        <section className="py-12 md:py-20 bg-muted/50">
            <div className="container mx-auto px-4">
                <div className="text-center max-w-3xl mx-auto">
                    <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">Powerful Dashboard</h2>
                    <p className="text-lg text-muted-foreground mt-4">
                        A glimpse into the control center. Here's a look at what our users see.
                    </p>
                </div>
                 <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
                    <div className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Total Revenue
                        </CardTitle>
                        <DollarSign className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                        <div className="text-2xl font-bold">৳45,231.89</div>
                        <p className="text-xs text-muted-foreground">
                            +20.1% from last month
                        </p>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Subscriptions
                        </CardTitle>
                        <Users className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                        <div className="text-2xl font-bold">+2350</div>
                        <p className="text-xs text-muted-foreground">
                            +180.1% from last month
                        </p>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Users</CardTitle>
                        <UserCircle className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                        <div className="text-2xl font-bold">12,234</div>
                        <p className="text-xs text-muted-foreground">
                            +19% from last month
                        </p>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Active Now</CardTitle>
                        <Activity className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                        <div className="text-2xl font-bold">+573</div>
                        <p className="text-xs text-muted-foreground">
                            +201 since last hour
                        </p>
                        </CardContent>
                    </Card>
                    </div>
                    <div className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3">
                    <Card className="xl:col-span-2">
                        <CardHeader>
                        <CardTitle>User Sign-ups</CardTitle>
                        <CardDescription>Last 6 Months</CardDescription>
                        </CardHeader>
                        <CardContent>
                        <ResponsiveContainer width="100%" height={350}>
                            <BarChart data={userSignups}>
                            <CartesianGrid strokeDasharray="3 3" />
                            <XAxis
                                dataKey="month"
                                stroke="#888888"
                                fontSize={12}
                                tickLine={false}
                                axisLine={false}
                            />
                            <YAxis
                                stroke="#888888"
                                fontSize={12}
                                tickLine={false}
                                axisLine={false}
                                tickFormatter={(value) => `${value}`}
                            />
                            <Tooltip
                                cursor={{fill: 'hsl(var(--muted))'}}
                                contentStyle={{backgroundColor: 'hsl(var(--background))', border: '1px solid hsl(var(--border))'}}
                            />
                            <Legend />
                            <Bar dataKey="signups" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
                            </BarChart>
                        </ResponsiveContainer>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                        <CardTitle>Recent Activity</CardTitle>
                        <CardDescription>
                            New users and subscriptions.
                        </CardDescription>
                        </CardHeader>
                        <CardContent className="grid gap-8">
                            {recentActivities.map((activity, index) => (
                                <div key={`activity-${index}-${activity.email}`} className="flex items-center gap-4">
                                    <Avatar className="hidden h-9 w-9 sm:flex">
                                    <AvatarFallback>{activity.name.charAt(0)}</AvatarFallback>
                                    </Avatar>
                                    <div className="grid gap-1">
                                    <p className="text-sm font-medium leading-none">{activity.name}</p>
                                    <p className="text-sm text-muted-foreground">
                                        {activity.email}
                                    </p>
                                    </div>
                                    <div className="ml-auto font-medium">
                                        <Badge variant={activity.type === 'Subscription' ? 'default' : 'secondary'}>
                                            {activity.amount}
                                        </Badge>
                                    </div>
                                </div>
                            ))}
                        </CardContent>
                    </Card>
                    </div>
                </main>
            </div>
        </section>


         {/* Pricing Section */}
          <section id="pricing" className="py-12 md:py-20 bg-background">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      <Badge variant="secondary" className="text-sm py-1 px-3 border-2 border-primary/50 text-primary mb-4">
                          🔥 Limited Time Launch Offer - 25% OFF with LAUNCH25
                      </Badge>
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">
                          Choose Your AI Content Creation Plan
                      </h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          All tools on this site are free. However, if you need more power and features, consider our premium plans.
                      </p>
                  </div>

                  {loading ? (
                      <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 items-start">
                          {[...Array(3)].map((_, i) => <Skeleton key={i} className="h-[500px] w-full" />)}
                      </div>
                  ) : (
                  <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 items-start">
                      {pricingPlans.map((plan, index) => (
                      <Card key={`pricing-${plan.id}-${index}`} className={`shadow-lg flex flex-col h-full transform hover:-translate-y-2 transition-transform duration-300 ${plan.isPopular ? 'border-2 border-primary' : ''}`}>
                          {plan.isPopular && <Badge className="absolute -top-3 left-1/2 -translate-x-1/2">MOST POPULAR + 25% OFF</Badge>}
                          <CardHeader>
                              <CardTitle className="text-2xl font-bold">{plan.name}</CardTitle>
                              <div className="flex items-baseline gap-2">
                                  <p className="text-4xl font-bold text-primary">৳{plan.price}</p>
                                  <p className="text-xl font-medium text-muted-foreground line-through">৳{plan.originalPrice}</p>
                                  <Badge variant="destructive">{plan.discount}</Badge>
                              </div>
                              <p className="text-muted-foreground pt-2">{plan.description}</p>
                              <p className="text-sm text-accent font-semibold">Use code: LAUNCH25 at checkout</p>
                          </CardHeader>
                          <CardContent className="flex-grow space-y-4">
                              <div className={`p-3 rounded-lg text-center ${plan.isPopular ? 'bg-primary/10' : 'bg-muted'}`}>
                                  <p className={`text-lg font-bold ${plan.isPopular ? 'text-primary' : ''}`}>{plan.credits} Credits</p>
                                  <p className="text-sm text-muted-foreground">Valid for {plan.validity}</p>
                              </div>
                              <div className="space-y-3 text-sm">
                                  {Object.entries(plan.features).map(([category, features]) => (
                                      <div key={category}>
                                          <h4 className="font-semibold text-base pt-2">{category}</h4>
                                          <ul className="space-y-2">
                                              {(features as string[]).map(feature => (
                                                  <li key={feature} className="flex items-center gap-2 text-muted-foreground"><Check className="w-4 h-4 text-green-500" /> {feature}</li>
                                              ))}
                                          </ul>
                                      </div>
                                  ))}
                              </div>
                          </CardContent>
                          <CardFooter>
                              <Button size="lg" className="w-full" asChild>
                                  <Link href="/#pricing">GET STARTED</Link>
                              </Button>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
                  )}
                  
                  {/* bKash Payment */}
                  <div className="mt-8 text-center">
                      <p className="text-sm text-muted-foreground">Pay with</p>
                      <div className="flex justify-center items-center gap-2 mt-2">
                          <svg className="h-8" viewBox="0 0 1024 372.48" xmlns="http://www.w3.org/2000/svg"><path d="M789.28 206.01c-6.22-9.45-14.28-17.51-24.16-24.16-29.4-19.8-67.65-27.42-105.1-27.42-83.82 0-155.22 55.45-180.12 131.25H259.9a185.53 185.53 0 0 1 185.16-184.81c50.78 0 96.84 19.89 130.82 51.69a183.88 183.88 0 0 1 51.51 130.64h-74.01a113.88 113.88 0 0 0-50.1-107.19z" fill="#D82A7D"/><path d="M575.83 293.36a110.87 110.87 0 0 0-21.57 2.37A111.43 111.43 0 0 0 445.89 404H244.66a185.53 185.53 0 0 1 327-133.4 114.1 114.1 0 0 0-38.33-22.95 183.85 183.85 0 0 1-57.5 145.71z" fill="#D82A7D"/><path d="M837.74 34.33h-134.3v271.85a33.15 33.15 0 0 0 33.15 33.15h101.15V34.33z" fill="#D82A7D"/><path d="M1024 34.33H889.67v305h101.18a33.15 33.15 0 0 0 33.15-33.15V34.33z" fill="#D82A7D"/><path d="M0 34.33h201.23v305H0z" fill="#D82A7D"/><path d="M371.84 34.33H237.5v305h134.34a33.15 33.15 0 0 0 33.15-33.15V67.48a33.15 33.15 0 0 0-33.15-33.15z" fill="#D82A7D"/></svg>
                          <p className="text-muted-foreground font-semibold">Easy mobile payments available for Bangladeshi users</p>
                      </div>
                  </div>
              </div>
          </section>

          {/* FAQ Section */}
          <section className="py-12 md:py-20">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">Frequently Asked Questions</h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          Everything you need to know about TotthoAi and our content generation tools.
                      </p>
                  </div>
                  <div className="mt-12 max-w-4xl mx-auto">
                      <Accordion type="single" collapsible className="w-full">
                          {faqItems.map((item, index) => (
                             <AccordionItem value={`item-${index}`} key={index}>
                                  <AccordionTrigger className="text-lg text-left font-semibold hover:no-underline">{item.question}</AccordionTrigger>
                                  <AccordionContent className="text-base text-muted-foreground">
                                      {item.answer}
                                  </AccordionContent>
                              </AccordionItem>
                          ))}
                      </Accordion>
                  </div>
                  <div className="text-center mt-8">
                       <p className="text-muted-foreground">Still have questions? <Link href="#" className="text-primary font-semibold hover:underline">Contact our support team</Link></p>
                  </div>
              </div>
          </section>
      </div>
    </>
  );

    



