
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ArrowRight, Bot, PenSquare, ShoppingCart, Languages, Hash, Briefcase, Mail, Lightbulb, FileText, GraduationCap, HelpCircle, BookCheck, Image as ImageIcon, DollarSign, Wand, FileSignature, Globe, Film, Mic, Code, Presentation, Palette, Gamepad, MessageSquare, UserCircle as UserCircleIcon, Edit, Layers, RefreshCcw, TowerControl, Sparkles as SparklesIcon, Zap, PlayCircle, Users, ThumbsUp, ShieldCheck, GanttChartSquare, ChevronDown, Link as LinkIcon, Activity, ArrowUpRight, CreditCard, Search, Clapperboard, Receipt, BarChart2, List, PanelTopOpen, CalendarDays, GitBranchPlus, LayoutTemplate, Megaphone, TrendingUp, Award, Clock, CheckCircle, Youtube, BarChart, Quote, X, Star } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PricingPlan } from '@/services/pricing-service';
import { Testimonial } from '@/services/testimonial-service';
import { Skeleton } from '@/components/ui/skeleton';
import type { Tool } from '@/services/tool-service';
import type { Coupon } from "@/services/coupon-service";
import React, { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "./ui/dialog";

const faqItems = [
    {
        question: "What is TotthoAi?",
        answer: "TotthoAi is an advanced AI content generation platform designed to help content creators, marketers, and businesses create high-quality, SEO-optimized content in over 150 languages, with a special focus on Bengali."
    },
    {
        question: "How do credits work?",
        answer: "Credits are used to generate content. For example, generating a full-length article might consume a certain number of credits. Your plan determines how many credits you receive, and you can see your remaining balance in your dashboard."
    },
    {
        question: "What happens if I run out of credits?",
        answer: "If you run out of credits, you can easily upgrade to a higher plan to get more credits. You can also purchase credit packs as needed without changing your subscription."
    },
    {
        question: "How does the content generation process work?",
        answer: "Our process is simple. With the One-Click Writer, you just provide a title, and our AI handles research, writing, formatting, and even image generation. For bulk generation, you can upload a CSV file with multiple titles."
    },
    {
        question: "What types of content can TotthoAi create?",
        answer: "TotthoAi can create a wide variety of content, including blog posts, news articles, product descriptions, social media captions, professional emails, and much more. It can also generate stunning AI images."
    },
    {
        question: "Is the generated content original and plagiarism-free?",
        answer: "Yes, all content generated by TotthoAi is 100% original and passes plagiarism checks. Our AI is designed to create unique content from scratch based on the prompts and data it analyzes."
    },
     {
        question: "How do I publish content to my website?",
        answer: "We offer seamless integration with WordPress, allowing you to publish your generated articles directly to your TotthoAi dashboard."
    },
    {
        question: "What's the difference between the One-click Generator and the Bulk Content Generator?",
        answer: "The One-Click Generator is perfect for creating individual, high-quality articles quickly. The Bulk Content Generator is designed for scale, allowing you to create hundreds of articles at once by uploading a list of titles."
    },
    {
        question: "How does the Content Refresh Tool work?",
        answer: "The Content Refresh Tool analyzes your existing articles, identifies outdated information, and updates them with the latest data, improved SEO, and fresh formatting to boost their performance."
    },
    {
        question: "What image generation capabilities does TotthoAi offer?",
        answer: "Our Enhanced AI Images can generate contextual, high-resolution images that are perfectly suited to your content, helping to increase reader engagement and visual appeal."
    },
    {
        question: "Can I customize the AI's writing style?",
        answer: "Absolutely. With our Custom AI Prompts feature, you can train the AI on your unique brand voice and writing style, ensuring all generated content is perfectly aligned with your brand."
    },
    {
        question: "Do you offer refunds if I'm not satisfied?",
        answer: "Yes, we have a refund policy. Please refer to our Refund Policy page for detailed information on the conditions and process for requesting a refund."
    },
    {
        question: "Can I upgrade or downgrade my subscription plan?",
        answer: "Yes, you can upgrade or downgrade your plan at any time directly from your account dashboard to better suit your content creation needs."
    },
    {
        question: "What support options are available?",
        answer: "We offer support via email and WhatsApp. Our dedicated support team is available to help you with any questions or issues you may have. Please visit our Contact page for more details."
    },
];

const trendingCategories = [
    { title: "কনটেন্ট ও লেখা", icon: PenSquare, href: "/ai-tools" },
    { title: "ছবি তৈরি", icon: ImageIcon, href: "/ai-tools" },
    { title: "প্রোডাক্টিভিটি ও ব্যবসা", icon: Briefcase, href: "/ai-tools" },
    { title: "এসইও ও মার্কেটিং", icon: TrendingUp, href: "/ai-tools" },
];

const iconMap: { [key: string]: React.ElementType } = {
    PenSquare, ShoppingCart, Languages, Hash, Briefcase, Mail, Lightbulb, FileText, GraduationCap, HelpCircle, BookCheck, ImageIcon, DollarSign, Wand, FileSignature, Globe, Film, Mic, Code, Presentation, Palette, Gamepad, MessageSquare, UserCircleIcon, Edit, Layers, RefreshCcw, Sparkles: SparklesIcon, TowerControl, Clapperboard, Youtube, Link: LinkIcon, Activity, ArrowUpRight, CreditCard, Award, CheckCircle, Clock, TrendingUp, Users, ThumbsUp, ShieldCheck, GanttChartSquare, ChevronDown, BarChart, Search, Receipt, LayoutTemplate, Megaphone, GitBranchPlus, List, PanelTopOpen, CalendarDays, BarChart2, Bot, Quote, Star
};

const packages = [
  {
    title: "দোকানদার প্যাকেজ",
    icon: ShoppingCart,
    description: "আপনার দোকানের日常প্রয়োজনীয় কনটেন্ট ও মার্কেটিং ম্যাটেরিয়াল তৈরি করুন দ্রুত এবং সহজে।",
    tools: [
      "AI Product Description Generator",
      "AI Poster & Banner Generator",
      "Social Media Caption Maker",
      "WhatsApp/FB Messenger Auto Reply Script",
      "Invoice & Bill Content Generator",
    ],
    useCase: "দোকানদাররা দ্রুত প্রফেশনাল কনটেন্ট বানাতে পারবে, অফার/ডিসকাউন্ট দিতে পারবে, পোস্টার/ক্যাপশন বানাতে পারবে।"
  },
  {
    title: "কনটেন্ট ক্রিয়েটর / ব্লগার প্যাকেজ",
    icon: PenSquare,
    description: "আপনার ব্লগ, ইউটিউব চ্যানেল বা সোশ্যাল মিডিয়ার জন্য SEO-অপ্টিমাইজড কনটেন্ট তৈরি করুন ১০ গুণ দ্রুত।",
    tools: [
      "AI Blog Writer (SEO Optimized)",
      "AI YouTube Script Generator",
      "Thumbnail Text + Image Ideas",
      "Keyword Research Helper",
      "Bengali/English Translator"
    ],
    useCase: "ব্লগার, ইউটিউবার, ইনফ্লুয়েন্সাররা ১০গুন দ্রুত কনটেন্ট তৈরি করতে পারবে।"
  },
  {
    title: "ডিজিটাল মার্কেটার প্যাকেজ",
    icon: Megaphone,
    description: "আপনার বিজ্ঞাপন, ইমেল এবং ল্যান্ডিং পেজের জন্য হাই-কনভার্টিং কপি তৈরি করে সেলস বাড়ান।",
    tools: [
      "FB/Instagram Ads Copy Generator",
      "Email Marketing Copy",
      "Landing Page Headline Generator",
      "A/B Testing Text Suggestions",
      "Hashtag Generator",
    ],
    useCase: "যারা ব্যবসা বা ব্র্যান্ড প্রোমোট করে তাদের জন্য।"
  },
  {
    title: "স্টুডেন্ট ও অ্যাকাডেমিক প্যাকেজ",
    icon: GraduationCap,
    description: "আপনার অ্যাসাইনমেন্ট, প্রেজেন্টেশন এবং গ্রামার সংক্রান্ত সমস্যা সমাধান করুন এক নিমিষে।",
    tools: [
      "Essay & Assignment Writer",
      "Bengali/English Summary Maker",
      "Grammar & Spelling Fixer",
      "Question → Answer Explainer",
      "Presentation Slide Content Generator"
    ],
    useCase: "যারা পড়াশোনায় সাহায্য চাইবে তাদের জন্য।"
  },
   {
    title: "কম্পিউটার ও টাইপিং শপ প্যাকেজ",
    icon: Briefcase,
    description: "আপনার দোকানের গ্রাহকদের জন্য আবেদনপত্র, সিভি, স্ট্যাম্প এবং অন্যান্য ডকুমেন্ট দ্রুত তৈরি করুন।",
    tools: [
      "Application & Letter Generator",
      "Resume & CV Builder",
      "Stamp & Certificate Text Generator",
      "Handwritten Text → Typed Text (OCR)",
      "Quick Typing Helper",
    ],
    useCase: "যারা কম্পিউটার দোকান চালায়, typing + print service দেয়, stamp/affidavit বানায় — তারা দ্রুত কাস্টমারদের জন্য কনটেন্ট বানাতে পারবে।"
  },
];

const newPricingPlans = [
    {
        id: "free",
        name: "Free Plan",
        price: 0,
        description: "দোকানদার ও ছোট ইউজারদের আকৃষ্ট করার জন্য।",
        features: ["Limited use of some tools", "5 Generations per month"],
        isPopular: false,
    },
    {
        id: "starter",
        name: "Starter",
        price: 499,
        description: "For individuals and small teams starting out.",
        features: ["Access to 5 tools", "200 Generations per month", "Standard Support"],
        isPopular: false,
    },
    {
        id: "pro",
        name: "Pro",
        price: 999,
        description: "For professionals who need more power.",
        features: ["Access to 15 tools", "1000 Generations per month", "Priority Support", "Early access to new features"],
        isPopular: true,
    },
    {
        id: "business",
        name: "Business",
        price: 1999,
        description: "For businesses and agencies with high demand.",
        features: ["Access to all tools", "Unlimited Generations (basic)", "Priority Access & Support"],
        isPopular: false,
    }
]


interface HomePageClientProps {
    testimonials: Testimonial[];
    trendingTools: Tool[];
    activeCoupons: Coupon[];
}

export default function HomePageClient({ testimonials, trendingTools, activeCoupons }: HomePageClientProps) {
  const [isMounted, setIsMounted] = React.useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const loading = !testimonials || !trendingTools;
  const primaryCoupon = activeCoupons && activeCoupons.length > 0 ? activeCoupons[0] : null;

  React.useEffect(() => {
    setIsMounted(true);
    const popupShown = Cookies.get('promoPopupShown');
    if (!popupShown) {
        // Show the popup after a short delay
        const timer = setTimeout(() => {
            setShowPopup(true);
            // Set a cookie that expires in 1 day
            Cookies.set('promoPopupShown', 'true', { expires: 1 });
        }, 3000);
        return () => clearTimeout(timer);
    }
  }, []);

  const closePopup = () => {
    setShowPopup(false);
  };

  return (
      <div className="flex flex-col bg-background">
        <Dialog open={showPopup} onOpenChange={setShowPopup}>
            <DialogContent className="p-0 max-w-lg overflow-hidden border-0">
                <div className="relative aspect-video">
                    <Image src="https://picsum.photos/600/400" alt="AI Image Editor" className="object-cover w-full h-full" width={600} height={400} data-ai-hint="abstract technology" />
                     <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/>
                </div>
                 <div className="p-6 absolute bottom-0 text-white">
                    <Badge variant="destructive" className="mb-2">New Tool!</Badge>
                    <DialogTitle className="text-2xl font-bold font-headline mt-2">AI Image Editor</DialogTitle>
                    <DialogDescription className="text-white/80 mt-2">
                         Edit images with simple text prompts. Change backgrounds, add objects, or transform styles instantly!
                    </DialogDescription>
                    <Button className="mt-4" asChild>
                        <Link href="/ai-tools/image-editor">Try it Now</Link>
                     </Button>
                </div>
            </DialogContent>
        </Dialog>


        {/* Hero Section */}
        <section className="py-16 md:py-24 bg-muted/30">
          <div className="container mx-auto px-4 text-center">
             <div className="max-w-4xl mx-auto">
                <h1 className="font-headline text-5xl md:text-7xl font-bold tracking-tight animate-fade-in-up">
                আপনার কনটেন্ট তৈরি করুন ১০ গুণ দ্রুত, সম্পূর্ণ বাংলায়
                </h1>
                <p className="text-lg text-muted-foreground mt-6 max-w-3xl mx-auto animate-fade-in-up [animation-delay:200ms]">
                TotthoAi ব্যবহার করে সময় ও অর্থ বাঁচান। SEO-অপ্টিমাইজড আর্টিকেল, সোশ্যাল মিডিয়া পোস্ট, এবং আকর্ষণীয় ছবি তৈরি করুন এক ক্লিকে।
                </p>
                <div className="mt-8 flex justify-center gap-4 animate-fade-in-up [animation-delay:400ms]">
                    <Button size="lg" className="text-base" asChild>
                        <Link href="/login">
                            <Zap className="mr-2 h-5 w-5"/>
                            বিনামূল্যে শুরু করুন
                        </Link>
                    </Button>
                    <Button size="lg" variant="outline" className="text-base" asChild>
                        <Link href="/ai-tools">
                           সকল টুলস দেখুন
                        </Link>
                    </Button>
                </div>
             </div>
          </div>
        </section>

        {/* Packages Section */}
        <section className="py-12 md:py-20">
            <div className="container mx-auto px-4">
                 <div className="text-center max-w-3xl mx-auto">
                    <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">আপনার প্রয়োজন অনুযায়ী প্যাকেজ</h2>
                    <p className="text-lg text-muted-foreground mt-4">
                        আপনার পেশা যাই হোক না কেন, আমাদের কাছে আপনার জন্য সঠিক টুলস এবং প্যাকেজ রয়েছে।
                    </p>
                </div>
                <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {packages.map((pkg) => {
                        const Icon = pkg.icon;
                        return (
                            <Card key={pkg.title} className="shadow-md hover:shadow-xl hover:border-primary transition-all duration-300 transform hover:-translate-y-1 h-full flex flex-col">
                                <CardHeader className="p-6">
                                    <div className="flex items-center gap-4">
                                        <div className="bg-primary/10 p-3 rounded-lg">
                                            <Icon className="w-8 h-8 text-primary"/>
                                        </div>
                                        <CardTitle className="text-xl">{pkg.title}</CardTitle>
                                    </div>
                                    <p className="text-sm text-muted-foreground pt-2">{pkg.description}</p>
                                </CardHeader>
                                <CardContent className="flex-grow px-6">
                                  <h4 className="font-semibold text-sm mb-2">Included Tools:</h4>
                                   <ul className="space-y-1.5 text-xs text-muted-foreground">
                                        {pkg.tools.map(tool => (
                                            <li key={tool} className="flex items-center gap-2">
                                                <CheckCircle className="w-3.5 h-3.5 text-green-500" /> {tool}
                                            </li>
                                        ))}
                                    </ul>
                                </CardContent>
                                <CardFooter className="p-6 pt-4">
                                     <Button variant="link" className="p-0">
                                        Explore Package <ArrowRight className="ml-2 w-4 h-4"/>
                                     </Button>
                                </CardFooter>
                            </Card>
                        );
                    })}
                </div>
            </div>
        </section>


        {/* Trending Tools Section */}
        <section id="trending-tools" className="py-12 md:py-20 bg-muted/50">
          <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">ট্রেন্ডিং টুলস</h2>
                  <p className="text-lg text-muted-foreground mt-4">
                     আমাদের ব্যবহারকারীদের মধ্যে সবচেয়ে জনপ্রিয় এবং বহুল ব্যবহৃত টুলগুলো দেখুন।
                  </p>
              </div>
              <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                   {loading ? (
                       [...Array(4)].map((_, i) => <Skeleton key={i} className="h-64 w-full" />)
                   ) : (
                       trendingTools.map(tool => {
                            const Icon = iconMap[tool.icon] || Bot;
                            return (
                                <Link href={tool.href} key={tool.id} className="group">
                                    <Card className="h-full flex flex-col justify-between shadow-md hover:shadow-xl hover:border-primary transition-all duration-300 transform hover:-translate-y-1">
                                        <CardHeader className="flex flex-row items-start gap-4">
                                            <div className="bg-primary/10 p-3 rounded-md">
                                                <Icon className="w-8 h-8 text-primary" />
                                            </div>
                                            <div>
                                                <CardTitle className="text-xl">{tool.title}</CardTitle>
                                            </div>
                                        </CardHeader>
                                        <CardContent>
                                            <p className="text-muted-foreground text-sm">{tool.description}</p>
                                        </CardContent>
                                        <CardFooter className="p-4 pt-0 flex justify-end">
                                            <ArrowRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors" />
                                        </CardFooter>
                                    </Card>
                                </Link>
                            )
                       })
                   )}
              </div>
               <div className="text-center mt-12">
                   <Button size="lg" asChild>
                      <Link href="/ai-tools">
                          <Search className="mr-2 h-5 w-5"/>
                          সকল টুল দেখুন
                      </Link>
                  </Button>
              </div>
          </div>
        </section>

         {/* Pricing Section */}
          <section id="pricing" className="py-12 md:py-20">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">
                          Choose Your AI Content Creation Plan
                      </h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          All tools on this site are free. However, if you need more power and features, consider our premium plans.
                      </p>
                  </div>

                  <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 items-start">
                      {newPricingPlans.map((plan, index) => (
                      <Card key={plan.id} className={`shadow-lg flex flex-col h-full transform hover:-translate-y-2 transition-transform duration-300 ${plan.isPopular ? 'border-2 border-primary' : ''}`}>
                          {plan.isPopular && <Badge className="absolute -top-3 left-1/2 -translate-x-1/2">MOST POPULAR</Badge>}
                          <CardHeader>
                              <CardTitle className="text-2xl font-bold">{plan.name}</CardTitle>
                              <p className="text-muted-foreground pt-2 h-12">{plan.description}</p>
                              <div className="flex items-baseline gap-2 pt-4">
                                  <p className="text-4xl font-bold text-primary">৳{plan.price}</p>
                                  {plan.id !== 'free' && <span className="text-sm text-muted-foreground">/ মাস</span>}
                              </div>
                          </CardHeader>
                          <CardContent className="flex-grow space-y-4">
                              <ul className="space-y-3 text-sm">
                                  {plan.features.map(feature => (
                                      <li key={feature} className="flex items-center gap-2 text-muted-foreground"><CheckCircle className="w-4 h-4 text-green-500" /> {feature}</li>
                                  ))}
                              </ul>
                          </CardContent>
                          <CardFooter>
                              <Button size="lg" className="w-full" asChild>
                                  <Link href="/dashboard/pricing">{plan.id === 'free' ? 'Get Started' : 'Choose Plan'}</Link>
                              </Button>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
              </div>
          </section>
        
        {/* Success Stories Section */}
          <section className="py-12 md:py-20 bg-muted/50">
              <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">Success Stories with TotthoAi</h2>
                  <p className="text-lg text-muted-foreground mt-4 animate-fade-in-up [animation-delay:200ms]">
                  Real Results from Real Users. See how content creators, marketers, and businesses are achieving extraordinary results with our features.
                  </p>
                  <div className="mt-8 grid grid-cols-1 sm:grid-cols-3 gap-4 text-center animate-fade-in-up [animation-delay:400ms]">
                      <p className="font-semibold text-lg">Avg. 90% time savings</p>
                      <p className="font-semibold text-lg">300% faster creation</p>
                      <p className="font-semibold text-lg">2x better SEO results</p>
                  </div>
              </div>
               {loading ? (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {[...Array(4)].map((_, i) => <Skeleton key={i} className="h-64 w-full" />)}
                  </div>
               ) : (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {testimonials.map((testimonial, index) => (
                      <Card key={testimonial.id} className="shadow-lg animate-fade-in-up" style={{animationDelay: `${600 + index*100}ms`}}>
                          <CardHeader>
                              <CardTitle className="text-xl">{testimonial.feature}</CardTitle>
                          </CardHeader>
                          <CardContent>
                              <p className="text-muted-foreground text-sm italic">"{testimonial.quote}"</p>
                              <p className="mt-4 font-bold text-primary">{testimonial.metric}</p>
                          </CardContent>
                          <CardFooter className="flex items-center gap-3">
                              <Avatar>
                                  <AvatarImage src={testimonial.avatar} data-ai-hint={testimonial.dataAiHint}/>
                                  <AvatarFallback>{testimonial.authorName.charAt(0)}</AvatarFallback>
                              </Avatar>
                              <div>
                                  <p className="font-semibold">{testimonial.authorName}</p>
                                  <p className="text-xs text-muted-foreground">{testimonial.authorRole}</p>
                              </div>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
              )}
              <div className="text-center mt-12 animate-fade-in-up">
                      <Button size="lg" asChild>
                      <Link href="/dashboard/pricing">
                          Start Your Success Story
                      </Link>
                  </Button>
              </div>
              </div>
          </section>

          {/* FAQ Section */}
          <section className="py-12 md:py-20">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">Frequently Asked Questions</h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          Everything you need to know about TotthoAi and our content generation tools.
                      </p>
                  </div>
                  <div className="mt-12 max-w-4xl mx-auto">
                      {!isMounted ? (
                        <div className="space-y-4">
                          {[...Array(5)].map((_, i) => <Skeleton key={i} className="h-16 w-full" />)}
                        </div>
                      ) : (
                        <Accordion type="single" collapsible className="w-full">
                            {faqItems.map((item, index) => (
                               <AccordionItem value={`item-${index}`} key={index}>
                                    <AccordionTrigger className="text-lg text-left font-semibold hover:no-underline">{item.question}</AccordionTrigger>
                                    <AccordionContent className="text-base text-muted-foreground">
                                        {item.answer}
                                    </AccordionContent>
                                </AccordionItem>
                            ))}
                        </Accordion>
                      )}
                  </div>
                  <div className="text-center mt-8">
                       <p className="text-muted-foreground">Still have questions? <Link href="/contact" className="text-primary font-semibold hover:underline">Contact our support team</Link></p>
                  </div>
              </div>
          </section>
      </div>
  );

}

    