
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ArrowRight, Bot, PenSquare, ShoppingCart, Languages, Hash, Briefcase, Mail, Lightbulb, FileText, GraduationCap, HelpCircle, BookCheck, Image as ImageIcon, DollarSign, Wand, FileSignature, Globe, Film, Mic, Code, Presentation, Palette, Gamepad, MessageSquare, UserCircle as UserCircleIcon, Edit, Layers, RefreshCcw, TowerControl, Sparkles as SparklesIcon, Zap, PlayCircle, Users, ThumbsUp, ShieldCheck, GanttChartSquare, ChevronDown, Link as LinkIcon, Activity, ArrowUpRight, CreditCard, Search, Clapperboard, Receipt, BarChart2, List, PanelTopOpen, CalendarDays, GitBranchPlus, LayoutTemplate, Megaphone, TrendingUp, Award, Clock, CheckCircle, Youtube, BarChart, Quote, X } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PricingPlan } from '@/services/pricing-service';
import { Testimonial } from '@/services/testimonial-service';
import { Skeleton } from '@/components/ui/skeleton';
import type { Tool } from '@/services/tool-service';
import type { Coupon } from "@/services/coupon-service";
import React, { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "./ui/dialog";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "./ui/carousel";
import Autoplay from "embla-carousel-autoplay";


const faqItems = [
    {
        question: "What is TotthoAi?",
        answer: "TotthoAi is an advanced AI content generation platform designed to help content creators, marketers, and businesses create high-quality, SEO-optimized content in over 150 languages, with a special focus on Bengali."
    },
    {
        question: "How do credits work?",
        answer: "Credits are used to generate content. For example, generating a full-length article might consume a certain number of credits. Your plan determines how many credits you receive, and you can see your remaining balance in your dashboard."
    },
    {
        question: "What happens if I run out of credits?",
        answer: "If you run out of credits, you can easily upgrade to a higher plan to get more credits. You can also purchase credit packs as needed without changing your subscription."
    },
    {
        question: "How does the content generation process work?",
        answer: "Our process is simple. With the One-Click Writer, you just provide a title, and our AI handles research, writing, formatting, and even image generation. For bulk generation, you can upload a CSV file with multiple titles."
    },
    {
        question: "What types of content can TotthoAi create?",
        answer: "TotthoAi can create a wide variety of content, including blog posts, news articles, product descriptions, social media captions, professional emails, and much more. It can also generate stunning AI images."
    },
    {
        question: "Is the generated content original and plagiarism-free?",
        answer: "Yes, all content generated by TotthoAi is 100% original and passes plagiarism checks. Our AI is designed to create unique content from scratch based on the prompts and data it analyzes."
    },
     {
        question: "How do I publish content to my website?",
        answer: "We offer seamless integration with WordPress, allowing you to publish your generated articles directly to your TotthoAi dashboard."
    },
    {
        question: "What's the difference between the One-click Generator and the Bulk Content Generator?",
        answer: "The One-Click Generator is perfect for creating individual, high-quality articles quickly. The Bulk Content Generator is designed for scale, allowing you to create hundreds of articles at once by uploading a list of titles."
    },
    {
        question: "How does the Content Refresh Tool work?",
        answer: "The Content Refresh Tool analyzes your existing articles, identifies outdated information, and updates them with the latest data, improved SEO, and fresh formatting to boost their performance."
    },
    {
        question: "What image generation capabilities does TotthoAi offer?",
        answer: "Our Enhanced AI Images 2.0 can generate contextual, high-resolution images that are perfectly suited to your content, helping to increase reader engagement and visual appeal."
    },
    {
        question: "Can I customize the AI's writing style?",
        answer: "Absolutely. With our Custom AI Prompts feature, you can train the AI on your unique brand voice and writing style, ensuring all generated content is perfectly aligned with your brand."
    },
    {
        question: "Do you offer refunds if I'm not satisfied?",
        answer: "Yes, we have a refund policy. Please refer to our Refund Policy page for detailed information on the conditions and process for requesting a refund."
    },
    {
        question: "Can I upgrade or downgrade my subscription plan?",
        answer: "Yes, you can upgrade or downgrade your plan at any time directly from your account dashboard to better suit your content creation needs."
    },
    {
        question: "What support options are available?",
        answer: "We offer support via email and WhatsApp. Our dedicated support team is available to help you with any questions or issues you may have. Please visit our Contact page for more details."
    },
];

const trendingCategories = [
    { title: "কনটেন্ট ও লেখা", icon: PenSquare, href: "/ai-tools" },
    { title: "ছবি তৈরি", icon: ImageIcon, href: "/ai-tools" },
    { title: "প্রোডাক্টিভিটি ও ব্যবসা", icon: Briefcase, href: "/ai-tools" },
    { title: "এসইও ও মার্কেটিং", icon: TrendingUp, href: "/ai-tools" },
];

const iconMap: { [key: string]: React.ElementType } = {
    PenSquare, ShoppingCart, Languages, Hash, Briefcase, Mail, Lightbulb, FileText, GraduationCap, HelpCircle, BookCheck, ImageIcon, DollarSign, Wand, FileSignature, Globe, Film, Mic, Code, Presentation, Palette, Gamepad, MessageSquare, UserCircleIcon, Edit, Layers, RefreshCcw, Sparkles: SparklesIcon, TowerControl, Clapperboard, Youtube, Link: LinkIcon, Activity, ArrowUpRight, CreditCard, Award, CheckCircle, Clock, TrendingUp, Users, ThumbsUp, ShieldCheck, GanttChartSquare, ChevronDown, BarChart, Search, Receipt, LayoutTemplate, Megaphone, GitBranchPlus, List, PanelTopOpen, CalendarDays, BarChart2, Bot, Quote
};

const featuredTools = [
  {
    title: "One-Click Article Writer",
    description: "Generate a full blog post from a single title. SEO-optimized and ready to publish.",
    href: "/ai-tools/one-click-writer",
    icon: SparklesIcon,
  },
  {
    title: "Facebook Comment Generator",
    description: "Instantly create relevant comments and replies for any Facebook post or image.",
    href: "/ai-tools/facebook-comment-generator",
    icon: MessageSquare,
  },
  {
    title: "AI Image Generator",
    description: "Turn your text descriptions into stunning, high-quality images for any purpose.",
    href: "/ai-tools/image-generator",
    icon: ImageIcon,
  },
   {
    title: "AI Image Editor",
    description: "Edit any image with a simple text prompt using our new Nano Banana model.",
    href: "/ai-tools/image-editor",
    icon: Palette,
  },
];


interface HomePageClientProps {
    pricingPlans: PricingPlan[];
    testimonials: Testimonial[];
    trendingTools: Tool[];
    activeCoupons: Coupon[];
}

export default function HomePageClient({ pricingPlans, testimonials, trendingTools, activeCoupons }: HomePageClientProps) {
  const [isMounted, setIsMounted] = React.useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const loading = !pricingPlans || !testimonials || !trendingTools;
  const primaryCoupon = activeCoupons && activeCoupons.length > 0 ? activeCoupons[0] : null;

  React.useEffect(() => {
    setIsMounted(true);
    const popupShown = Cookies.get('promoPopupShown');
    if (!popupShown) {
        // Show the popup after a short delay
        const timer = setTimeout(() => {
            setShowPopup(true);
            // Set a cookie that expires in 1 day
            Cookies.set('promoPopupShown', 'true', { expires: 1 });
        }, 3000);
        return () => clearTimeout(timer);
    }
  }, []);

  const closePopup = () => {
    setShowPopup(false);
  };
  
  const sliderItems = [
    {
      title: "আপনার সৃজনশীলতা প্রকাশ করুন",
      description: "TotthoAi-এর সাহায্যে যেকোনো ধরনের কনটেন্ট তৈরি করুন, ছবি বানান এবং আপনার ব্যবসাকে নতুন উচ্চতায় নিয়ে যান।",
      image: "https://picsum.photos/1200/800",
      dataAiHint: "man professional",
      href: "/ai-tools"
    },
    {
      title: "শক্তিশালী AI টুলস ব্যবহার করুন",
      description: "আমাদের প্ল্যাটফর্মে রয়েছে ১৫০টিরও বেশি ভাষায় কনটেন্ট তৈরির সুবিধা, যা আপনার কাজকে আরও সহজ করে তুলবে।",
      image: "https://picsum.photos/1200/600",
      dataAiHint: "technology abstract",
      href: "/ai-tools"
    },
    {
      title: "আমাদের কমিউনিটিতে যোগ দিন",
      description: "হাজারো কনটেন্ট ক্রিয়েটর এবং ফ্রিল্যান্সারদের সাথে যুক্ত হয়ে নতুন কিছু শিখুন এবং আপনার অভিজ্ঞতা শেয়ার করুন।",
      image: "https://picsum.photos/1200/600",
      dataAiHint: "community working",
      href: "/community"
    },
  ]


  return (
      <div className="flex flex-col bg-background">
        <Dialog open={showPopup} onOpenChange={setShowPopup}>
            <DialogContent className="p-0 max-w-lg overflow-hidden border-0">
                <div className="relative aspect-video">
                    <Image src="https://picsum.photos/600/400" alt="AI Image Editor" fill className="object-cover"/>
                     <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/>
                </div>
                 <div className="p-6 absolute bottom-0 text-white">
                    <Badge variant="destructive" className="mb-2">New Tool!</Badge>
                    <DialogTitle className="text-2xl font-bold font-headline mt-2">AI Image Editor</DialogTitle>
                    <DialogDescription className="text-white/80 mt-2">
                         Edit images with simple text prompts. Change backgrounds, add objects, or transform styles instantly!
                    </DialogDescription>
                    <Button className="mt-4" asChild>
                        <Link href="/ai-tools/image-editor">Try it Now</Link>
                     </Button>
                </div>
            </DialogContent>
        </Dialog>


        {/* Hero Section */}
        <section className="pt-8 pb-8 overflow-hidden bg-muted/30">
          <div className="container mx-auto px-4">
             <Carousel 
                opts={{ loop: true }} 
                plugins={[Autoplay({delay: 5000})]}
                className="w-full"
            >
                <CarouselContent>
                    {sliderItems.map((item, index) => (
                    <CarouselItem key={index}>
                        <Card className="border-none shadow-none bg-transparent">
                        <CardContent className="p-0">
                            <div className="grid grid-cols-1 md:grid-cols-2 items-center gap-8">
                                <div className="text-center md:text-left animate-fade-in-up">
                                    <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tight">
                                        {item.title}
                                    </h1>
                                    <p className="text-lg text-muted-foreground mt-6">
                                        {item.description}
                                    </p>
                                    <div className="mt-8">
                                         <Button size="lg" className="transition-transform transform hover:scale-105 text-base shadow-lg" asChild>
                                            <Link href={item.href}>
                                                <Zap className="mr-2 h-5 w-5"/>
                                                আরও জানুন
                                            </Link>
                                        </Button>
                                    </div>
                                </div>
                                <div className="relative w-full h-64 md:h-96 animate-fade-in-up [animation-delay:200ms]">
                                    <Image 
                                        src={item.image} 
                                        alt={item.title} 
                                        fill
                                        className="object-cover rounded-lg shadow-xl"
                                        data-ai-hint={item.dataAiHint}
                                    />
                                </div>
                            </div>
                        </CardContent>
                        </Card>
                    </CarouselItem>
                    ))}
                </CarouselContent>
                <CarouselPrevious className="left-4" />
                <CarouselNext className="right-4" />
            </Carousel>
          </div>
        </section>

        {/* Featured Tools Section */}
        <section className="py-12 md:py-20">
            <div className="container mx-auto px-4">
                 <div className="text-center max-w-3xl mx-auto">
                    <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">প্রয়োজনীয় টুলস</h2>
                    <p className="text-lg text-muted-foreground mt-4">
                        আমাদের সবচেয়ে জনপ্রিয় এবং শক্তিশালী টুলগুলো যা আপনার কাজকে সহজ করে তুলবে।
                    </p>
                </div>
                <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
                    {featuredTools.map((tool) => {
                        const Icon = tool.icon;
                        return (
                            <Link href={tool.href} key={tool.title}>
                                <Card className="text-center p-6 shadow-md hover:shadow-xl hover:border-primary transition-all duration-300 transform hover:-translate-y-1 h-full flex flex-col">
                                    <CardHeader className="p-0 items-center">
                                        <div className="bg-primary/10 p-4 rounded-full mb-4">
                                            <Icon className="w-8 h-8 text-primary"/>
                                        </div>
                                        <CardTitle>{tool.title}</CardTitle>
                                    </CardHeader>
                                    <CardContent className="flex-grow">
                                      <p className="text-sm text-muted-foreground mt-2">{tool.description}</p>
                                    </CardContent>
                                </Card>
                            </Link>
                        );
                    })}
                </div>
            </div>
        </section>


        {/* Trending Tools Section */}
        <section id="trending-tools" className="py-12 md:py-20 bg-muted/50">
          <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">ট্রেন্ডিং টুলস</h2>
                  <p className="text-lg text-muted-foreground mt-4">
                     আমাদের ব্যবহারকারীদের মধ্যে সবচেয়ে জনপ্রিয় এবং বহুল ব্যবহৃত টুলগুলো দেখুন।
                  </p>
              </div>
              <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                   {loading ? (
                       [...Array(4)].map((_, i) => <Skeleton key={i} className="h-64 w-full" />)
                   ) : (
                       trendingTools.map(tool => {
                            const Icon = iconMap[tool.icon] || Bot;
                            return (
                                <Link href={tool.href} key={tool.id} className="group">
                                    <Card className="h-full flex flex-col justify-between shadow-md hover:shadow-xl hover:border-primary transition-all duration-300 transform hover:-translate-y-1">
                                        <CardHeader className="flex flex-row items-start gap-4">
                                            <div className="bg-primary/10 p-3 rounded-md">
                                                <Icon className="w-8 h-8 text-primary" />
                                            </div>
                                            <div>
                                                <CardTitle className="text-xl">{tool.title}</CardTitle>
                                            </div>
                                        </CardHeader>
                                        <CardContent>
                                            <p className="text-muted-foreground text-sm">{tool.description}</p>
                                        </CardContent>
                                        <CardFooter className="p-4 pt-0 flex justify-end">
                                            <ArrowRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors" />
                                        </CardFooter>
                                    </Card>
                                </Link>
                            )
                       })
                   )}
              </div>
               <div className="text-center mt-12">
                   <Button size="lg" asChild>
                      <Link href="/ai-tools">
                          <Search className="mr-2 h-5 w-5"/>
                          সকল টুল দেখুন
                      </Link>
                  </Button>
              </div>
          </div>
        </section>

        {/* What's New Section */}
        <section id="whats-new" className="py-12 md:py-20">
          <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">What's New in TotthoAi 2.0</h2>
                  <p className="text-lg text-muted-foreground mt-4 animate-fade-in-up [animation-delay:200ms]">
                      Experience the next generation of AI-powered content creation with features designed to save time, boost quality, and scale your content strategy like never before.
                  </p>
              </div>
              <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                   <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:400ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <Clock className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">90% Time Savings</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-sm text-muted-foreground">Automate tedious tasks and generate high-quality content in seconds, not hours.</p>
                      </CardContent>
                  </Card>
                  <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:600ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <TrendingUp className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">Better SEO Results</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-sm text-muted-foreground">Create content that is optimized for search engines to rank higher and drive more traffic.</p>
                      </CardContent>
                  </Card>
                  <Card className="text-center shadow-lg p-4 animate-fade-in-up [animation-delay:800ms]">
                      <CardHeader>
                          <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-2">
                              <Award className="w-8 h-8 text-primary" />
                          </div>
                          <CardTitle className="text-xl font-bold">Professional Quality</CardTitle>
                      </CardHeader>
                      <CardContent>
                          <p className="text-sm text-muted-foreground">Generate well-structured, coherent, and engaging articles that rival human writers.</p>
                      </CardContent>
                  </Card>
              </div>
          </div>
        </section>

         {/* Detailed Features */}
         <section id="features" className="py-12 md:pt-20 bg-muted/50">
              <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
                   <div className="md:col-span-2 lg:col-span-1 lg:pr-8 animate-fade-in-up">
                      <Badge variant="destructive">🔥 HOT NEW FEATURE</Badge>
                      <h3 className="text-3xl font-bold mt-2">Video to Blog Post</h3>
                      <p className="text-muted-foreground mt-4">Transform any YouTube video into a comprehensive, SEO-optimized blog post in minutes. Extract insights, create outlines, and generate complete articles from video content.</p>
                   </div>
                   <div className="md:col-span-2 grid grid-cols-2 sm:grid-cols-3 gap-8">
                      <div className="space-y-2 animate-fade-in-up [animation-delay:200ms]">
                          <ImageIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Enhanced AI Images 2.0</h4>
                          <p className="text-sm text-muted-foreground">Generate stunning, contextual images that boost engagement by 300%.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:300ms]">
                          <LinkIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Smart Internal Linking</h4>
                          <p className="text-sm text-muted-foreground">Automatically create SEO-friendly internal links to improve site authority.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:400ms]">
                          <SparklesIcon className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Custom AI Prompts</h4>
                          <p className="text-sm text-muted-foreground">Train the AI with your unique voice and style for brand consistency.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:500ms]">
                          <Languages className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">150+ Languages Support</h4>
                          <p className="text-sm text-muted-foreground">Create content in Bengali, English, Hindi, Arabic, and more.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:600ms]">
                          <Layers className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Bulk Generation 2.0</h4>
                          <p className="text-sm text-muted-foreground">Create hundreds of articles simultaneously with our advanced engine.</p>
                      </div>
                       <div className="space-y-2 animate-fade-in-up [animation-delay:700ms]">
                          <RefreshCcw className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Content Refresh Tool</h4>
                          <p className="text-sm text-muted-foreground">Instantly update old content with fresh information and improved SEO.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:800ms]">
                          <TowerControl className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">Topical Authority Builder</h4>
                          <p className="text-sm text-muted-foreground">Build topic clusters to establish your site as a niche authority.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:900ms]">
                          <PenSquare className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">One-Click Writer 2.0</h4>
                          <p className="text-sm text-muted-foreground">Generate publication-ready articles with just one click.</p>
                      </div>
                        <div className="space-y-2 animate-fade-in-up [animation-delay:1000ms]">
                          <FileText className="w-8 h-8 text-primary"/>
                          <h4 className="font-semibold">News Writer 2.0</h4>
                          <p className="text-sm text-muted-foreground">Create timely, accurate news articles with real-time data integration.</p>
                      </div>
                   </div>
              </div>
               <div className="text-center mt-12 animate-fade-in-up [animation-delay:1100ms]">
                   <Button size="lg" asChild>
                      <Link href="/ai-tools">
                          <Zap className="mr-2 h-5 w-5"/>
                          Explore All Tools
                      </Link>
                  </Button>
              </div>
         </section>
        
        {/* Success Stories Section */}
          <section className="py-12 md:py-20">
              <div className="container mx-auto px-4">
              <div className="text-center max-w-3xl mx-auto">
                  <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight animate-fade-in-up">Success Stories with TotthoAi 2.0</h2>
                  <p className="text-lg text-muted-foreground mt-4 animate-fade-in-up [animation-delay:200ms]">
                  Real Results from Real Users. See how content creators, marketers, and businesses are achieving extraordinary results with our new 2.0 features.
                  </p>
                  <div className="mt-8 grid grid-cols-1 sm:grid-cols-3 gap-4 text-center animate-fade-in-up [animation-delay:400ms]">
                      <p className="font-semibold text-lg">Avg. 90% time savings</p>
                      <p className="font-semibold text-lg">300% faster creation</p>
                      <p className="font-semibold text-lg">2x better SEO results</p>
                  </div>
              </div>
               {loading ? (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {[...Array(4)].map((_, i) => <Skeleton key={i} className="h-64 w-full" />)}
                  </div>
               ) : (
                  <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                      {testimonials.map((testimonial, index) => (
                      <Card key={testimonial.id} className="shadow-lg animate-fade-in-up" style={{animationDelay: `\'\'\'${600 + index*100}\'\'\'ms`}}>
                          <CardHeader>
                              <CardTitle className="text-xl">{testimonial.feature}</CardTitle>
                          </CardHeader>
                          <CardContent>
                              <p className="text-muted-foreground text-sm italic">"{testimonial.quote}"</p>
                              <p className="mt-4 font-bold text-primary">{testimonial.metric}</p>
                          </CardContent>
                          <CardFooter className="flex items-center gap-3">
                              <Avatar>
                                  <AvatarImage src={testimonial.avatar} data-ai-hint={testimonial.dataAiHint}/>
                                  <AvatarFallback>{testimonial.authorName.charAt(0)}</AvatarFallback>
                              </Avatar>
                              <div>
                                  <p className="font-semibold">{testimonial.authorName}</p>
                                  <p className="text-xs text-muted-foreground">{testimonial.authorRole}</p>
                              </div>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
              )}
              <div className="text-center mt-12 animate-fade-in-up">
                      <Button size="lg" asChild>
                      <Link href="/dashboard/pricing">
                          Start Your Success Story
                      </Link>
                  </Button>
              </div>
              </div>
          </section>

         {/* Pricing Section */}
          <section id="pricing" className="py-12 md:py-20 bg-muted/50">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      {primaryCoupon && (
                        <Badge variant="secondary" className="text-sm py-1.5 px-4 border-2 border-primary/50 text-primary mb-4">
                            🔥 {primaryCoupon.description || `Limited Time Offer - Use code ${primaryCoupon.code}`}
                        </Badge>
                      )}
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">
                          Choose Your AI Content Creation Plan
                      </h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          All tools on this site are free. However, if you need more power and features, consider our premium plans.
                      </p>
                  </div>

                  {loading ? (
                      <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 items-start">
                          {[...Array(3)].map((_, i) => <Skeleton key={i} className="h-[500px] w-full" />)}
                      </div>
                  ) : (
                  <div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 items-start">
                      {pricingPlans.map((plan, index) => (
                      <Card key={`pricing-${plan.id}-${index}`} className={`shadow-lg flex flex-col h-full transform hover:-translate-y-2 transition-transform duration-300 ${plan.isPopular ? 'border-2 border-primary' : ''}`}>
                          {plan.isPopular && <Badge className="absolute -top-3 left-1/2 -translate-x-1/2">MOST POPULAR</Badge>}
                          <CardHeader>
                              <CardTitle className="text-2xl font-bold">{plan.name}</CardTitle>
                              <div className="flex items-baseline gap-2">
                                  <p className="text-4xl font-bold text-primary">৳{plan.price}</p>
                                  <p className="text-xl font-medium text-muted-foreground line-through">৳{plan.originalPrice}</p>
                                  {plan.discount && <Badge variant="destructive">{plan.discount}</Badge>}
                              </div>
                              <p className="text-muted-foreground pt-2">{plan.description}</p>
                              {primaryCoupon && (
                                <p className="text-sm text-accent font-semibold">Use code: {primaryCoupon.code} at checkout for {primaryCoupon.discountPercentage}% off!</p>
                              )}
                          </CardHeader>
                          <CardContent className="flex-grow space-y-4">
                              <div className={`p-3 rounded-lg text-center ${plan.isPopular ? 'bg-primary/10' : 'bg-muted'}`}>
                                  <p className={`text-lg font-bold ${plan.isPopular ? 'text-primary' : ''}`}>{plan.credits} Credits</p>
                                  <p className="text-sm text-muted-foreground">Valid for {plan.validity}</p>
                              </div>
                              <div className="space-y-3 text-sm">
                                  {Object.entries(plan.features).map(([category, features]) => (
                                      <div key={category}>
                                          <h4 className="font-semibold text-base pt-2">{category}</h4>
                                          <ul className="space-y-2">
                                              {(features as string[]).map(feature => (
                                                  <li key={feature} className="flex items-center gap-2 text-muted-foreground"><CheckCircle className="w-4 h-4 text-green-500" /> {feature}</li>
                                              ))}
                                          </ul>
                                      </div>
                                  ))}
                              </div>
                          </CardContent>
                          <CardFooter>
                              <Button size="lg" className="w-full" asChild>
                                  <Link href="/dashboard/pricing">GET STARTED</Link>
                              </Button>
                          </CardFooter>
                      </Card>
                      ))}
                  </div>
                  )}
                  
                  {/* bKash Payment */}
                  <div className="mt-8 text-center">
                      <p className="text-sm text-muted-foreground">Pay with</p>
                      <div className="flex justify-center items-center gap-2 mt-2">
                          <svg className="h-8" viewBox="0 0 1024 372.48" xmlns="http://www.w3.org/2000/svg"><path d="M789.28 206.01c-6.22-9.45-14.28-17.51-24.16-24.16-29.4-19.8-67.65-27.42-105.1-27.42-83.82 0-155.22 55.45-180.12 131.25H259.9a185.53 185.53 0 0 1 185.16-184.81c50.78 0 96.84 19.89 130.82 51.69a183.88 183.88 0 0 1 51.51 130.64h-74.01a113.88 113.88 0 0 0-50.1-107.19z" fill="#D82A7D"/><path d="M575.83 293.36a110.87 110.87 0 0 0-21.57 2.37A111.43 111.43 0 0 0 445.89 404H244.66a185.53 185.53 0 0 1 327-133.4 114.1 114.1 0 0 0-38.33-22.95 183.85 183.85 0 0 1-57.5 145.71z" fill="#D82A7D"/><path d="M837.74 34.33h-134.3v271.85a33.15 33.15 0 0 0 33.15 33.15h101.15V34.33z" fill="#D82A7D"/><path d="M1024 34.33H889.67v305h101.18a33.15 33.15 0 0 0 33.15-33.15V34.33z" fill="#D82A7D"/><path d="M0 34.33h201.23v305H0z" fill="#D82A7D"/><path d="M371.84 34.33H237.5v305h134.34a33.15 33.15 0 0 0 33.15-33.15V67.48a33.15 33.15 0 0 0-33.15-33.15z" fill="#D82A7D"/></svg>
                          <p className="text-muted-foreground font-semibold">Easy mobile payments available for Bangladeshi users</p>
                      </div>
                  </div>
              </div>
          </section>

          {/* FAQ Section */}
          <section className="py-12 md:py-20">
              <div className="container mx-auto px-4">
                  <div className="text-center max-w-3xl mx-auto">
                      <h2 className="font-headline text-4xl md:text-5xl font-bold tracking-tight">Frequently Asked Questions</h2>
                      <p className="text-lg text-muted-foreground mt-4">
                          Everything you need to know about TotthoAi and our content generation tools.
                      </p>
                  </div>
                  <div className="mt-12 max-w-4xl mx-auto">
                      {!isMounted ? (
                        <div className="space-y-4">
                          {[...Array(5)].map((_, i) => <Skeleton key={i} className="h-16 w-full" />)}
                        </div>
                      ) : (
                        <Accordion type="single" collapsible className="w-full">
                            {faqItems.map((item, index) => (
                               <AccordionItem value={`item-${index}`} key={index}>
                                    <AccordionTrigger className="text-lg text-left font-semibold hover:no-underline">{item.question}</AccordionTrigger>
                                    <AccordionContent className="text-base text-muted-foreground">
                                        {item.answer}
                                    </AccordionContent>
                                </AccordionItem>
                            ))}
                        </Accordion>
                      )}
                  </div>
                  <div className="text-center mt-8">
                       <p className="text-muted-foreground">Still have questions? <Link href="/contact" className="text-primary font-semibold hover:underline">Contact our support team</Link></p>
                  </div>
              </div>
          </section>
      </div>
  );

}

    